name: Terraform Plan
on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v3

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v2
      with:
        version: 1.4.6

    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Terraform Plan
      id: run-terraform-plan
      run: |
        cd tf_code
        terraform init
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json

    - name: Setup OPA
      id: setup-opa
      uses: open-policy-agent/setup-opa@v2
      with:
        version: 0.42

    - name: Run OPA query
      id: run-opa-query
      run: |
        echo "OPA_OUTPUT=$(opa eval data.main.allow -f pretty -i tf_code/tfplan.json -d .github/opa/example_policy.rego)" >> $GITHUB_OUTPUT


    - name: Check policy violations
      id: check-policy-violations
      run: |
        if [ "${{ steps.run-opa-query.outputs.OPA_OUTPUT }}" != "true" ]; then exit 1; fi
