name: Terraform Plan
on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        version: 1.4.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Terraform Plan
      run: |
        cd tf_code
        terraform init
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: 0.42

    - name: Run OPA query
      run: opa eval data.main.allow -f pretty -i tfplan.json -d .github/opa/example_policy.rego

    - name: Check if any policy violations
      run: |
        if [ "${{ steps.opa.outputs }}" != "true" ]; then exit 1; fi
